#pragma once

enum
	//GUI identifiers
{
	TOOLBOXLIST = 1,
	TBXNAMEMSG = 2,
	TBXNAMEENTRY = 3,
	TBXDELETE = 4,
	LOADSESSION = 5,
	SAVESESSION = 6,
	SAVESESSIONAS = 7,
	TBXOPENFILE = 8,
	SESSIONOPENFILE = 9,
	NAMESESSION = 10,
	SESSIONNAMEENTRY = 11,
	SESSIONLOADCONFIRM = 12,
	NAMESTACK = 13,
	NAMESTACKENTRY = 14,
	TOOLBOXCONTEXT = 900,
	TOOLBOX = 1000
};